# https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules
# Higher zip compression for the zip archives -
compressionLevel: mixed
# We currently copy cache out of .yarn/cache which we should update to make use of the global cache
enableGlobalCache: false
# Show logs for build from source in standard output instead of in file
enableInlineBuilds: true
