[build]
  command = "NEXT_SKIP_TYPECHECK=true next build --no-lint"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--force"

[[plugins]]
  package = "@netlify/plugin-nextjs" 