name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (defaults shown)
          types: |
            fix
            feat
            chore
            docs
            style
            refactor
            perf
            test
            build
            ci
            revert
          # Configure additional validation for the subject based on a regex.
          # This example ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          # If the PR contains multiple commits, only the title is checked
          validateSingleCommit: false
          # If the PR contains a single commit, the commit message is used as well
          validateSingleCommitMatchesPrTitle: true
          # Allows skipping validation for PRs with specific labels
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
