name: Sync Examples

on:
  push:
    branches: [main]
    paths:
      - 'examples/**'
      - '.github/workflows/sync-examples.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: source

      - name: Clone or init target
        run: |
          # Try to clone the repository
          if git clone --depth 1 https://${{ secrets.EXAMPLES_PAT }}@github.com/sqlrooms/examples.git target; then
            echo "Successfully cloned target repository"
          else
            # If clone fails, initialize a new repository
            mkdir target
            cd target
            git init
            git remote add origin https://${{ secrets.EXAMPLES_PAT }}@github.com/sqlrooms/examples.git
            echo "# SQLRooms Examples" > README.md
            git add README.md
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Initial commit"
            git branch -M main
            git push -u origin main
            cd ..
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Sync examples
        run: |
          # Copy examples directory
          rm -rf target/* !target/.git
          cp -r source/examples/* target/

          # Update package.json files
          find target -name "package.json" -type f | while read -r file; do
            # Replace all "@sqlrooms/*": "workspace:*" with "@sqlrooms/*": "latest"
            jq '(.dependencies | with_entries(if .key | startswith("@sqlrooms/") then .value = "latest" else . end)) as $deps | .dependencies = $deps' "$file" > temp.json
            mv temp.json "$file"
          done

          # Setup git config
          cd target
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit and push changes
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync examples from main repo (${GITHUB_SHA})"
            git push
          fi
